package Game;

public interface Constants {
  int DEFAULT_VERTICAL_SEPARATOR_START_X = 300;
  int DEFAULT_VERTICAL_SEPARATOR_END_X = 300;
  int DEFAULT_VERTICAL_SEPARATOR_END_Y = 300;
  int DEFAULT_HORIZONTAL_SEPARATOR_SIZE = 300;
  int DEFAULT_WINDOW_WIDTH = 500;
  int DEFAULT_WINDOW_HEIGHT = 300;
  int  DEFAULT_SIZE = 3;
  int DEFAULT_DISTANCE_BETWEEN_DOTS = 50;
}
